on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

     

     - name: "login to docker hub"
       run: docker login --username ${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }}


      - name: "building docker image"
        run: docker build -t ${{ secrets.USERNAME }}/myimage .

      - name: "pushing to docker hup"
        run: docker push ${{ secrets.USERNAME }}/myimage 
